// Generated from: tests\features\Dashboard.feature
import { test } from "../../../tests/fixtures/Fixtures.js";

test.describe('Dashboard Functionality', () => {

  test.beforeEach('Background: Login to Manan portal', async ({ Given, homePage, And, signinPage, When, Then }) => {
    await Given('The user enter correct Manan portal URL', null, { homePage }); 
    await And('User Click on Sign in button', null, { signinPage }); 
    await When('When User enters valid Email Address and Password', null, { signinPage }); 
    await And('User click on SignIn button', null, { signinPage }); 
    await Then('Then User should be redirected to Manan App page "https://manan.numpyninja.com/app"', null, { signinPage }); 
  });
  
  test('Verify that the user is able to navigate to Dashboard page after clicking Dashboard button in the Manan page', async ({ When, dashboardPage, Then }) => { 
    await When('The user clicks on Dashboard button in the Manan page', null, { dashboardPage }); 
    await Then('The user is able to view the title "Welcome to Your Medical Dashboard" in the Dashboard page', null, { dashboardPage }); 
  });

  test('Verify that the user is able to view "Start New Assessment" button in the Dashboard page', async ({ Given, dashboardPage, Then }) => { 
    await Given('The user is in the Dashboard page', null, { dashboardPage }); 
    await Then('The user is able to view Start New Assessment button in the Dashboard page', null, { dashboardPage }); 
  });

  test('Verify that the user is able to click "Start New Assessment" button in the Dashboard page', async ({ Given, dashboardPage, When, Then }) => { 
    await Given('The user is in the Dashboard page', null, { dashboardPage }); 
    await When('The user clicks Start New Assessment button in the Dashboard page', null, { dashboardPage }); 
    await Then('The user is navigated to the Manan page', null, { dashboardPage }); 
  });

  test('Verify that the user is able to view "View Previous Assessments" button in the Dashboard page', async ({ Given, dashboardPage, Then }) => { 
    await Given('The user is in the Dashboard page', null, { dashboardPage }); 
    await Then('The user is able to view the button in the Dashboard page', null, { dashboardPage }); 
  });

  test('Verify that the user is able to click "View Previous Assessments" button in the Dashboard page', async ({ Given, dashboardPage, When, Then }) => { 
    await Given('The user is in the Dashboard page', null, { dashboardPage }); 
    await When('The user clicks View Previous Assessments button in the Dashboard page', null, { dashboardPage }); 
    await Then('The user is navigated to the Previous Assessments page', null, { dashboardPage }); 
  });

  test('Verify that the user is able to view "Your Assessments" in the Previous Assessments page when there are records present', async ({ Given, dashboardPage, Then }) => { 
    await Given('The user is in the Previous Assessments page', null, { dashboardPage }); 
    await Then('The user is able to view Your Assessments in the Previous Assessments page', null, { dashboardPage }); 
  });

  test('Verify that the user is able to view two tabs "Assessment" and "Case Details" after clicking one of the previous assessments', async ({ Given, dashboardPage, Then }) => { 
    await Given('The user is in the Previous Assessments page', null, { dashboardPage }); 
    await Then('The user is able to view the two tabs in the previous assessments', null, { dashboardPage }); 
  });

  test('Verify that the user is able to view "Assessment" tab after selecting the assessment', async ({ Given, dashboardPage, Then }) => { 
    await Given('The user is in the Previous Assessments page', null, { dashboardPage }); 
    await Then('The user is able to view Assessment tab after selecting the assessment', null, { dashboardPage }); 
  });

  test('Verify that the user is able to view "Case Details" after clicking "Case Details" tab in the Previous Assessments page', async ({ Given, dashboardPage, When, Then }) => { 
    await Given('The user is in the Previous Assessments page', null, { dashboardPage }); 
    await When('The user clicks Case Details tab in the Previous Assessments page', null, { dashboardPage }); 
    await Then('The user is able to view Case Details tab in the Previous Assessments page', null, { dashboardPage }); 
  });

  test('Verify that the user is able to choose anyone of the assessment when multiple assessments are present', async ({ Given, dashboardPage, When, Then }) => { 
    await Given('The user is in the Previous Assessments page', null, { dashboardPage }); 
    await When('The user clicks on anyone of the assessment when multiple assessments are present', null, { dashboardPage }); 
    await Then('The user is able to view the selected assessment when multiple assessments are present', null, { dashboardPage }); 
  });

  test('Verify that the user is able to export the assessment details in to a pdf file after clicking "Export as PDF"', async ({ Given, dashboardPage, When, Then }) => { 
    await Given('The user is in the Previous Assessments page', null, { dashboardPage }); 
    await When('The user clicks on Export as PDF button', null, { dashboardPage }); 
    await Then('The user is able to export the assessment details in to a pdf file', null, { dashboardPage }); 
  });

});

// == technical section ==

test.use({
  $test: ({}, use) => use(test),
  $uri: ({}, use) => use('tests\\features\\Dashboard.feature'),
  $bddFileData: ({}, use) => use(bddFileData),
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":14,"pickleLine":10,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":15,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"When The user clicks on Dashboard button in the Manan page","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"Then The user is able to view the title \"Welcome to Your Medical Dashboard\" in the Dashboard page","stepMatchArguments":[{"group":{"start":35,"value":"\"Welcome to Your Medical Dashboard\"","children":[{"start":36,"value":"Welcome to Your Medical Dashboard","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":19,"pickleLine":14,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":20,"gherkinStepLine":15,"keywordType":"Context","textWithKeyword":"Given The user is in the Dashboard page","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"Then The user is able to view Start New Assessment button in the Dashboard page","stepMatchArguments":[]}]},
  {"pwTestLine":24,"pickleLine":18,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":19,"keywordType":"Context","textWithKeyword":"Given The user is in the Dashboard page","stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":20,"keywordType":"Action","textWithKeyword":"When The user clicks Start New Assessment button in the Dashboard page","stepMatchArguments":[]},{"pwStepLine":27,"gherkinStepLine":21,"keywordType":"Outcome","textWithKeyword":"Then The user is navigated to the Manan page","stepMatchArguments":[]}]},
  {"pwTestLine":30,"pickleLine":23,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":24,"keywordType":"Context","textWithKeyword":"Given The user is in the Dashboard page","stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"Then The user is able to view the button in the Dashboard page","stepMatchArguments":[]}]},
  {"pwTestLine":35,"pickleLine":27,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":28,"keywordType":"Context","textWithKeyword":"Given The user is in the Dashboard page","stepMatchArguments":[]},{"pwStepLine":37,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"When The user clicks View Previous Assessments button in the Dashboard page","stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then The user is navigated to the Previous Assessments page","stepMatchArguments":[]}]},
  {"pwTestLine":41,"pickleLine":43,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":42,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"Given The user is in the Previous Assessments page","stepMatchArguments":[]},{"pwStepLine":43,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then The user is able to view Your Assessments in the Previous Assessments page","stepMatchArguments":[]}]},
  {"pwTestLine":46,"pickleLine":47,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":47,"gherkinStepLine":48,"keywordType":"Context","textWithKeyword":"Given The user is in the Previous Assessments page","stepMatchArguments":[]},{"pwStepLine":48,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then The user is able to view the two tabs in the previous assessments","stepMatchArguments":[]}]},
  {"pwTestLine":51,"pickleLine":51,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":52,"keywordType":"Context","textWithKeyword":"Given The user is in the Previous Assessments page","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":53,"keywordType":"Outcome","textWithKeyword":"Then The user is able to view Assessment tab after selecting the assessment","stepMatchArguments":[]}]},
  {"pwTestLine":56,"pickleLine":55,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":56,"keywordType":"Context","textWithKeyword":"Given The user is in the Previous Assessments page","stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":57,"keywordType":"Action","textWithKeyword":"When The user clicks Case Details tab in the Previous Assessments page","stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":58,"keywordType":"Outcome","textWithKeyword":"Then The user is able to view Case Details tab in the Previous Assessments page","stepMatchArguments":[]}]},
  {"pwTestLine":62,"pickleLine":60,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":63,"gherkinStepLine":61,"keywordType":"Context","textWithKeyword":"Given The user is in the Previous Assessments page","stepMatchArguments":[]},{"pwStepLine":64,"gherkinStepLine":62,"keywordType":"Action","textWithKeyword":"When The user clicks on anyone of the assessment when multiple assessments are present","stepMatchArguments":[]},{"pwStepLine":65,"gherkinStepLine":63,"keywordType":"Outcome","textWithKeyword":"Then The user is able to view the selected assessment when multiple assessments are present","stepMatchArguments":[]}]},
  {"pwTestLine":68,"pickleLine":65,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given The user enter correct Manan portal URL","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User Click on Sign in button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When When User enters valid Email Address and Password","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"And User click on SignIn button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then Then User should be redirected to Manan App page \"https://manan.numpyninja.com/app\"","isBg":true,"stepMatchArguments":[{"group":{"start":49,"value":"\"https://manan.numpyninja.com/app\"","children":[{"start":50,"value":"https://manan.numpyninja.com/app","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":66,"keywordType":"Context","textWithKeyword":"Given The user is in the Previous Assessments page","stepMatchArguments":[]},{"pwStepLine":70,"gherkinStepLine":67,"keywordType":"Action","textWithKeyword":"When The user clicks on Export as PDF button","stepMatchArguments":[]},{"pwStepLine":71,"gherkinStepLine":68,"keywordType":"Outcome","textWithKeyword":"Then The user is able to export the assessment details in to a pdf file","stepMatchArguments":[]}]},
]; // bdd-data-end